### PR TITLE
feat: auto translation plugin using GPT under the hood

### PR DESCRIPTION
**Pull request by byteHulk**
## Summary

添加大模型自动翻译插件

还有些优化工作:
~~dev server 不更新代码插入的文件~~
翻译效果提升

## Related Issue

#409 

## Checklist

- [x] I have added changeset via `pnpm run change`.
- [x] I have updated the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by sanyuan0704** [comment]
Maybe you should resolve the conflicts

**Comment by sanyuan0704** [comment]
Somehow i think the plugin could be a external plugin and maintained separately. And then we reserve its docs in rspress website.

**Comment by sanyuan0704** [comment]
@byteHulk How do you think it?

**Comment by byteHulk** [comment]
It's kind of like a community plug-in. It's not core functionality, is it?

**Comment by sanyuan0704** [comment]
> It's kind of like a community plug-in. It's not core functionality, is it?

yeah, that's right

**Comment by byteHulk** [comment]
> > It's kind of like a community plug-in. It's not core functionality, is it?
> 
> yeah, that's right

okey, I think there's no problem

**Comment by byteHulk** [comment]
> Somehow i think the plugin could be a external plugin and maintained separately. And then we reserve its docs in rspress website.

done

Plugin name changed to rspress-plugin-translate

**Comment by sanyuan0704** [comment]
Have you release the package?
image

**Comment by byteHulk** [comment]
> Have you release the package? image

It's a standard name, right?

**Comment by sanyuan0704** [comment]
Yeah

**Comment by byteHulk** [comment]
> Yeah

Released

**Comment by sanyuan0704** [comment]
> > Yeah
> 
> Released

OK

**Comment by chenjiahan** [comment]
We can also add it to https://github.com/web-infra-dev/awesome-rspack?tab=readme-ov-file#plugins 😄

**Pull request merged**
