### PR TITLE
feat: display title in frontmatter as heading fallback

### LINKED ISSUE #1440: [Feature]: Use font awesome `title: <title>` as H1 heading if no H1 heading is added
### What problem does this feature solve?

Given following example `index.md` file:

```md
---
title: Heading 1
---

## Heading 2

Some content
```

In Docusaurus this would add `Heading 1` as the title of the document. But in RSPress:

Image

One can add an additional `Heading 1` in the document, but then markdownlint will complain about the document having two top-level headings, MD025.

* <https://github.com/DavidAnson/markdownlint/blob/main/doc/md025.md>

Image

### What does the proposed API look like?

I have no idea.

### PR DESCRIPTION
**Pull request by JounQin**
## Related Issue

close #1440

## Checklist

- [x] Tests updated (or not required).
- [x] Documentation updated (or not required).

### CODE REVIEW

**Comment by Timeless0911** [comment]
Thanks, I think this should be an opt-in feature with documented.

**Comment by chenjiahan** [comment]
@Timeless0911 This feature should be the default behavior as it does not introduce breaking changes. Do you have any concerns?

**Comment by Timeless0911** [comment]
> @Timeless0911 This feature should be the default behavior as it does not introduce breaking changes. Do you have any concerns?

The behavior of automatically adding titles should be made optional with `exclude` options. Users may insert relevant titles by themselves through other slots or scripts, and we need some ways to disable this behavior on some pages such as overview page.

**Comment by chenjiahan** [comment]
> Users may insert relevant titles by themselves through other slots or scripts,

This doesn't seem to be common. It's relatively rare for the page title to be different from the h1 heading. I prefer providing an option to opt-out rather than opt-in.

**Comment by Timeless0911** [comment]
> This doesn't seem to be common. It's relatively rare for the page title to be different from the h1 heading. I prefer providing an option to opt-out rather than opt-in.

Agreed. Providing an options is needed, and the default value can be true though.📌

**Comment by JounQin** [comment]
I added an `fallbackHeadingTitle` themeConfig option.

**Review by Timeless0911 — APPROVED** [review]
LGTM

**Comment by JounQin** [comment]
> I remember that in overview component, we deal title in a specific way, can you compatible with this case?

The `title` already reads `frontmatter.title`. I'm not sure what you expect to render.

Current:

```mdx
---
overview: true
title: API Overview
---

# xxxx
```

image

```mdx
---
overview: true
---

# xxxx
```

image

**Comment by Timeless0911** [comment]
In this case, I think we should avoid to render two H1 in content?

**Comment by JounQin** [comment]
> In this case, I think we should avoid to render two H1 in content?

I believe this is out of scope of this PR, the behavior doesn't change between it, so maybe a new PR for it is more suitable.

> And what will be rendered if we write like below that without H1 xxxx

It doesn't change:

image

**Comment by Timeless0911** [comment]
Oh I forget that `Overview` do not use `docContent` to render. 

I think this PR is good enough to merge, thank you!

**Pull request merged**
