### PR TITLE
feat: respond to the change of system theme appearance

### PR DESCRIPTION
**Pull request by ambar**
## Summary

Splits:
- #878 also add `color-scheme` on root element, this is useful for theme styling based on native CSS media queries or `light-dark()` function, third-party libraries and creators may use this feature
- #879 

In this PR,  all the appearance related codes are refactored to a single React Hook, the checklist:

- [x] Should respond to system preference change (light/dark/auto)
- [x] Should respond to local storage change (every tab should be in sync)
- [x] Should be in sync with Media Query (prefers-color-scheme)
- [x] Should not flash in dev/prod mode
- [x] Should not break the usage of `window.RSPRESS_THEME`, however, the use of global variables is flawed, see comments beblow [#issuecomment-2027006896](#issuecomment-2027006896)

After these are done, we can use two patterns to display elements without flash:

```html
<!-- double element trick by class hook of Tailwind -->
<MyComponent className="dark:hidden" />
<MyComponent className="hidden dark:block" />

<!-- native CSS media query (image/video only) -->
<picture>
  <source srcset="dark.svg" media="(prefers-color-scheme: dark)" />
  <source srcset="light.svg" media="(prefers-color-scheme: light)" />
  <img src="light.svg" />
</picture>
```

## Checklist

- [x] I have added changeset via `pnpm run change`.
- [ ] I have updated the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by chenjiahan** [comment]
Hi, thanks for your contribution. ❤️

Can you make separate PRs for each change? It will help us to review the changes.

**Comment by ambar** [comment]
@chenjiahan It's possible, but the changes are dependent on each other, I can take a try.

**Comment by ambar** [comment]
@chenjiahan You could review #878, #879 first

**Comment by 10Derozan** [comment]
Nice, and we can remove theme context. @sanyuan0704

**Comment by 10Derozan** [comment]
But, have you tested it, I think it still flash in production when enable ssg.

**Comment by ambar** [comment]
It's working in the Netlify Preview, even if the JavaScript is turned off, the images will not flash.
Some thoughts:
- `RSPRESS_THEME`/`MODERN_THEME` could be removed (or add a option to theme config), as it cannot be reached in the inline theme script, this is a existing issue before this PR. If you're using it, you may see the theme flash after mount.
- We could add a option to hardcode the theme to `light` or `dark`, this will replaces the darkMode: boolean.

**Comment by Timeless0911** [comment]
replaces the darkMode: boolean seems to introduce some breaking change? How about expand the type of darkMode, maybe like this?

```ts
interface DarkModeSettings {
    toggleButton: boolean;
    defaultMode: "dark" | "light" | "auto";
}

type DarkModeConfig = boolean | DarkModeSettings;

darkMode?: DarkModeConfig;
```

**Review by Timeless0911 — DISMISSED** [review]

**Comment by Timeless0911** [comment]
hi，#878 and #879 have been merged~ You can continue your separate

**Comment by ambar** [comment]
@Timeless0911 Thanks, rebased, this is the last PR, updated the description.

**Review by sanyuan0704 — APPROVED** [review]

**Comment by sanyuan0704** [comment]
Awesome

**Review by Timeless0911 — APPROVED** [review]

**Pull request merged**
