### PR TITLE
fix: tabData undefined when syncIndex

### PR DESCRIPTION
**Pull request by Timeless0911**
## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by Timeless0911** [comment]
@shulaoda hi, I encoutered an issue like
image

Please help me to see if there is any problem with this fix pr.

**Comment by shulaoda** [comment]
> hi, I encoutered an issue like

The initial value of tabData is {}, should there be no problem under normal circumstances?

**Comment by Timeless0911** [comment]
https://github.com/web-infra-dev/rspress/blob/c8eee029ff02247abf12ef5ef3f914f9ff1e3c12/packages/theme-default/src/components/Search/SearchPanel.tsx#L315

I encouter this issue in this component

**Comment by shulaoda** [comment]
> I encouter this issue in this component

Have you started running? Or is it just a TS detection error

**Comment by Timeless0911** [comment]
runtime error, tabdata print out to be undefined. May be we should add some protection code.

**Comment by Timeless0911** [comment]
I was eating dinner earlier hh.

There is indeed a problem with the initialization here, after changing it, it behaves right. Awesome!

**Comment by Timeless0911** [comment]
!canary

**Review by SoonIter — APPROVED** [review]

**Pull request merged**
