### PR TITLE
feat(internal-components): New Steps Component!

### PR DESCRIPTION
**Pull request by ArnavK-09**
## Summary

image
image
image

## Checklist

- [x] I have added changeset via `pnpm run change`.
- [x] I have updated the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by sanyuan0704** [comment]
Amazing!

**Comment by sanyuan0704** [comment]
I think it's better to align in vertical direction:
image

**Comment by ArnavK-09** [comment]
> I think it's better to align in vertical direction: image

image

**Comment by sanyuan0704** [comment]
> I think it's better to align in vertical direction: image

Have you compat the UI the mobile device?

**Review by sanyuan0704 — APPROVED** [review]

**Comment by chenjiahan** [comment]
Cool 👍

**Pull request merged**
