### PR TITLE
Docs: add more community plugins

### PR DESCRIPTION
**Pull request by linbudu599**
## Summary

Add list of plugins from [rspress-plugins](https://github.com/linbudu599/rspress-plugins).

This `_meta.json` was updated by alphabetical order.

## Checklist

- [ ] Tests updated (or not required).
- [x] Documentation updated (or not required).

### CODE REVIEW

**Comment by chenjiahan** [comment]
Thank you for your contribution!

From my perspective, maintaining the documentation of all community plugins in the Rspress documentation site is not appropriate. This results in the community plugin's code and documentation not being maintained in the same place.

I suggest maintaining the documentation and code of the community plugins in the same repository, then add the repository link to Rspress website and [awesome-rspack](https://github.com/web-infra-dev/awesome-rspack). This allows users to discover and use these community plugins.

**Comment by linbudu599** [comment]
> Thank you for your contribution!
> 
> From my perspective, maintaining the documentation of all community plugins in the Rspress documentation site is not appropriate. This results in the community plugin's code and documentation not being maintained in the same place.
> 
> I suggest maintaining the documentation and code of the community plugins in the same repository, then add the repository link to Rspress website and [awesome-rspack](https://github.com/web-infra-dev/awesome-rspack). This allows users to discover and use these community plugins.

I actually think so, this synchronization process is indeed cumbersome enough, so I need to update the sidebar configuration to the absolute address to the plugin address?

**Comment by chenjiahan** [comment]
You can add the absolute address to this page: https://rspress.dev/plugin/official-plugins/overview.html#community-plugins

The left side bar should only contains official plugins, @Timeless0911 please check this

**Comment by linbudu599** [comment]
I would suggest to move community plugins to a seperate page like `community-plugins/overview` instead of a sub heading like `official-plugins/overview#community-plugins`.

The latest commit had made changes described above. cc @chenjiahan @Timeless0911

**Comment by Timeless0911** [comment]
LGTM

**Comment by Timeless0911** [comment]
It seems the doc about translate plugin is linked to rspress website as is shown in https://github.com/byteHulk/rspress-plugin-translate/blob/master/README.md

Do we need to contact the author to move the document to his plugin repo for maintenance? @chenjiahan

**Comment by chenjiahan** [comment]
> Do we need to contact the author to move the document to his plugin repo for maintenance? @chenjiahan

Sure, @byteHulk can you move the document of `rspress-plugin-translate` to its own repo? ❤️

**Review by chenjiahan — APPROVED** [review]
This PR will be merged once `rspress-plugin-translate' documentation has been completed.

**Comment by chenjiahan** [comment]
I will merge this PR first.

@byteHulk please help to move the document of rspress-plugin-translate to its own repo when you have time ❤️

**Pull request merged**
