### PR TITLE
feat: support replacement nav title

### LINKED ISSUE #1508: [Feature]: Make nav title replaceable
### What problem does this feature solve?

I want to replace the default nav title element:

https://github.com/web-infra-dev/rspress/blob/422a9d915eac6e459c78bb8a9a2da3b03b0fc66b/packages/theme-default/src/components/Nav/index.tsx#L140-L144

### What does the proposed API look like?

possible change:

```ts
interface NavProps {
    beforeNav?: React.ReactNode;
    beforeNavTitle?: React.ReactNode;
    navTitle?: React.ReactNode;
    afterNavTitle?: React.ReactNode;
    afterNavMenu?: React.ReactNode;
}
```

and update the tsx to:

```tsx
{navTitle ?? (<NavBarTitle />)}
```

### PR DESCRIPTION
**Pull request by Yukiniro**
## Summary
Closes #1508

## Checklist

- [x] Tests updated (or not required).
- [x] Documentation updated (or not required).

### CODE REVIEW

**Comment by Timeless0911** [comment]
LGTM for the pc devices, but when we use mobile devices, sidebar component will use `< NavBarTitle />` component too.

https://github.com/web-infra-dev/rspress/blob/7caec924a787e97d4e7b78cbd532b97783ef3233/packages/theme-default/src/components/Sidebar/index.tsx#L209-L213

image

You should also handle this scenario in an elegant way.

**Comment by Yukiniro** [comment]
> LGTM for the pc devices, but when we use mobile devices, sidebar component will use `< NavBarTitle />` component too.
> 
> https://github.com/web-infra-dev/rspress/blob/7caec924a787e97d4e7b78cbd532b97783ef3233/packages/theme-default/src/components/Sidebar/index.tsx#L209-L213
> 
> image
> 
> You should also handle this scenario in an elegant way.

Sorry, I missed it, I will add it later.

**Comment by Yukiniro** [comment]
updated 9eb7c010b24e6e62b8fab3b32bb8191a0654edde

**Review by Timeless0911 — APPROVED** [review]
👍

**Pull request merged**
