### PR TITLE
feat: add new component Toc

### PR DESCRIPTION
**Pull request by SnowingFox**
## Summary

Toc

## Details

add new component Toc

close https://github.com/web-infra-dev/rspress/issues/57

## Checklist

- [ ] I have added changeset via `pnpm run change`.
- [ ] I have updated the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by sanyuan0704** [comment]
Is there any preview image?

**Comment by SnowingFox** [comment]
image
@sanyuan0704

**Comment by sanyuan0704** [comment]
Nice work!

**Comment by SnowingFox** [comment]
image
what about this style?

**Pull request merged**
