### PR TITLE
feat(theme-default): hide aside element when no heading present

### PR DESCRIPTION
**Pull request by MaxtuneLee**
## Related Issue
closes: #915 

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by Timeless0911** [comment]
We'd better unified all logic that controls UI presentation in this function.

https://github.com/web-infra-dev/rspress/blob/70ebf18fc65ddf40715530767f72d490370446d9/packages/theme-default/src/logic/useUISwitch.ts#L18

**Comment by MaxtuneLee** [comment]
> We'd better unified all logic that controls UI presentation in this function.
> 
> https://github.com/web-infra-dev/rspress/blob/70ebf18fc65ddf40715530767f72d490370446d9/packages/theme-default/src/logic/useUISwitch.ts#L18

get it 👌

**Comment by Timeless0911** [comment]
Your alumni @9aoy

**Comment by MaxtuneLee** [comment]
> Your alumni @9aoy

haha, what a surprise 😮❕︎

**Comment by MaxtuneLee** [comment]
> We'd better unified all logic that controls UI presentation in this function.
> 
> https://github.com/web-infra-dev/rspress/blob/70ebf18fc65ddf40715530767f72d490370446d9/packages/theme-default/src/logic/useUISwitch.ts#L18

I've moved all the logic to useUISwitch, thanks for the review

**Comment by Timeless0911** [comment]
I think add `page.toc.length > 0 &&` is enough for this PR. The scene of no sidebar data already deal well?

**Comment by MaxtuneLee** [comment]
> I think add `page.toc.length > 0 &&` is enough for this PR. The scene of no sidebar data already deal well?

with `sidebarData.items.length > 0`
image

without `sidebarData.items.length > 0`
image

🤔️，I added that because I found that `Object.keys(sidebar).length > 0` is true even if there is no sidebar in current page

**Comment by Timeless0911** [comment]
image

I can not reproduce it.

My case is `e2e/fixtures/basic`

**Comment by MaxtuneLee** [comment]
> image
> 
> I can not reproduce it.
> 
> My case is `e2e/fixtures/basic`

It works perfectly when there is nothing else, but when we add more pages like
image
then we can reproduce this issue
image
I think this is because `localesData.sidebar` returns all sidebars in different pages by its path 
image

**Comment by Timeless0911** [comment]
I thought about it for a while and refered to the layout of [Vitepress](https://vitepress.dev/guide/mpa-mode) in such a cene that without headings in a doc.

The logic of this judgment is to reserve the placeholder sidebar and outline aside for the entire document. This is beneficial to the overall layout of the document  and also prevents the feeling of transition when switching each page in the document. 

At the same time, there are may be some height calculations logic in document layout that require dynamic layout by relying on some placeholder width.

For a special single page, we are more suitable to use [FrontMatter](https://rspress.dev/guide/basic/custom-page#using-fine-grained-switches) to control the display of related components for a separate page.


我想了一下，并参考了 [Vitepress](https://vitepress.dev/guide/mpa-mode) 在没有标题时候的布局。

这样判断的逻辑让文档的整体保留占位的 sidebar 和 outline aside，对于文档整体的布局是有益的，它使得文档中每个页面切换时不会产生瞬移的感觉。

同时，文档布局中可能还有一些高度的计算，需要依靠一些占位的模块来进行动态布局。

对于单页面的情况，我们更加适合使用 [FrontMatter](https://rspress.dev/guide/basic/custom-page#using-fine-grained-switches) 为单独的页面控制相关组件的展示。

@linbudu599 @MaxtuneLee cc What's your opinion?

**Comment by MaxtuneLee** [comment]
> I thought about it for a while and refered to the layout of [Vitepress](https://vitepress.dev/guide/mpa-mode) in such a scene that without headings in a doc.
> 
> The logic of this judgment is to reserve the placeholder sidebar and outline aside for the entire document. This is beneficial to the overall layout of the document and also prevents the feeling of transition when switching each page in the document.
> 
> At the same time, there are may be some height calculations logic in document layout that require dynamic layout by relying on some placeholder width.
> 
> For a special single page, we are more suitable to use [FrontMatter](https://rspress.dev/guide/basic/custom-page#using-fine-grained-switches) to control the display of related components for a separate page.
> 
> 我想了一下，并参考了 [Vitepress](https://vitepress.dev/guide/mpa-mode) 在没有标题时候的布局。
> 
> 这样判断的逻辑让文档的整体保留占位的 sidebar 和 outline aside，对于文档整体的布局是有益的，它使得文档中每个页面切换时不会产生瞬移的感觉。
> 
> 同时，文档布局中可能还有一些高度的计算，需要依靠一些占位的模块来进行动态布局。
> 
> 对于单页面的情况，我们更加适合使用 [FrontMatter](https://rspress.dev/guide/basic/custom-page#using-fine-grained-switches) 为单独的页面控制相关组件的展示。
> 
> @linbudu599 @MaxtuneLee cc What's your opinion?

I think ur right, reserving sidebar by default make page transition smoother, and we also have `sidebar` option to let users choose what they want, from overall consideration, I think this is reasonable to keep the sidebar.

**Comment by chenjiahan** [comment]
> The logic of this judgment is to reserve the placeholder sidebar and outline aside for the entire document. This is beneficial to the overall layout of the document and also prevents the feeling of transition when switching each page in the document.

Agreed 👍

**Comment by Timeless0911** [comment]
I will close this PR and its associated issues soon, thanks for your attention.

**Pull request closed without merging**
