### PR TITLE
feat(plugin-api-docgen): support jsdoc-to-markdown(#1351)

### PR DESCRIPTION
**Pull request by gaoachao**
## Related Issue
#1351

## Checklist

- [ ] Tests updated (or not required).
- [x] Documentation updated (or not required).

### CODE REVIEW

**Comment by SoonIter** [comment]
thanks for your contribution, could you add a e2e test case for this feature?

you can debug it with `npx playwright test --ui`

**Comment by SoonIter** [comment]
😭sorry, `jsdoc-to-markdown` seems that  it can only be used for parsing js files...
 it can only be used for eating.

**Comment by gaoachao** [comment]
Yeap, `jsdoc-to-markdown` can only process js files, not ts. But as a developer option, it also has some value. If we indicate in the document that `entries` needs to be js file.

**Comment by SoonIter** [comment]
> Yeap, `jsdoc-to-markdown` can only process js files, not ts. But as a developer option, it also has some value. If we indicate in the document that `entries` needs to be js file.

If few people use this feature, it will increase the maintenance cost and package size. 
Someone proposed to me to use `jsdoc-to-markdown`. He may just want to have a very simple tooling to extract comments of files, `documentation` extract not all the specific fields.

So sorry about the confusing issue, you could try out https://github.com/web-infra-dev/rspress/issues/1290

**Pull request closed without merging**
