### PR TITLE
fix(theme-default): doc container with full width.

### PR DESCRIPTION
**Pull request by sumy7**
## Summary

this pr use `width: 100%` not `calc(100vw - sidebar_width - outline_width)` to make doc container fill the entire width while screen width `>= 1280px` and `< 1440px`.

## Related Issue

https://github.com/web-infra-dev/rspress/pull/643#issuecomment-1964202075

## Checklist

- [ ] I have added changeset via `pnpm run change`.
- [ ] I have updated the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by sumy7** [comment]
Hi @sanyuan0704 @chenjiahan 

I apologize for the delay in addressing this issue due to recent busyness.
I have prepared a few test links. Could you please help to review whether the performance under different browser widths is okay? 

https://deploy-preview-677--aquamarine-blini-95325f.netlify.app/guide/start/introduction.html
https://deploy-preview-677--aquamarine-blini-95325f.netlify.app/guide/start/introduction.html?outline=0
https://deploy-preview-677--aquamarine-blini-95325f.netlify.app/guide/start/introduction.html?sidebar=0
https://deploy-preview-677--aquamarine-blini-95325f.netlify.app/guide/start/introduction.html?sidebar=0&outline=0

I've tested it myself and everything seems to be okay (approximately).

**Comment by chenjiahan** [comment]
Thanks! The current document width looks good in my device.

**Review by chenjiahan — APPROVED** [review]

**Review by sanyuan0704 — APPROVED** [review]

**Comment by chenjiahan** [comment]
@sumy7 find a bad case 😂 https://deploy-preview-1697--rsbuild.netlify.app/guide/basic/cli

image

**Comment by sumy7** [comment]
> @sumy7 find a bad case 😂 https://deploy-preview-1697--rsbuild.netlify.app/guide/basic/cli
> 
> image

Oops, the outline doesn't seem to have sufficient capabilities, perhaps a `min-width` is required.
I'll give it another try tomorrow!

**Pull request merged**
