### PR TITLE
feat(repress-hero-actions): better visibility on mobile/small screens!

### PR DESCRIPTION
**Pull request by ArnavK-09**
## Summary
This would have to get better visibility of hero actions on smaller screen, and looks better than before, proper padding and uniformity

## After 
Screenshot_2024-02-08-00-07-53-57_4d38fce200f96aeac5e860e739312e76

### Before
Screenshot_2024-02-08-00-09-57-88_4d38fce200f96aeac5e860e739312e76

## Checklist

- [ ] I have added changeset via `pnpm run change`.
- [ ] I have updated the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ArnavK-09** [comment]
Better to create it as feature in theme-docs, can be configured from config?

```ts
...
hero_actions: "verticle" | "horizontal"
...
```

**Comment by sanyuan0704** [comment]
Thank you

**Comment by sanyuan0704** [comment]
> Better to create it as feature in theme-docs, can be configured from config? In frontmatter 
> 
> ```yaml
> // ...
> hero:
>     actions: "verticle" | "horizontal"
> // ...
> ```

yeah，it can be configurable

**Comment by ArnavK-09** [comment]
> > Better to create it as feature in theme-docs, can be configured from config? In frontmatter 
> > 
> > ```yaml
> > // ...
> > hero:
> >     actions: "verticle" | "horizontal"
> > // ...
> > ```
> 
> yeah，it can be configurable

## should I pr this feature?
What's the flow? I just have to update types in press/shared & update logic in theme-default!
+ Update documentation guide...

Do I also need to update API section on docs or its automated?

**Comment by sanyuan0704** [comment]
> > > Better to create it as feature in theme-docs, can be configured from config? In frontmatter
> > > ```yaml
> > > // ...
> > > hero:
> > >     actions: "verticle" | "horizontal"
> > > // ...
> > > ```
> > 
> > 
> > yeah，it can be configurable
> 
> ## should I pr this feature?
> What's the flow? I just have to update types in press/shared & update logic in theme-default!
> 
> * Update documentation guide...
> 
> Do I also need to update API section on docs or its automated?

I think it's the actions layout type is not neccessary. Current style change in mobile device is just ok.

**Review by sanyuan0704 — APPROVED** [review]

**Comment by sanyuan0704** [comment]
Thank you

**Comment by ArnavK-09** [comment]
so it should be merged?

**Comment by sanyuan0704** [comment]
> so it should be merged?

No problem. I will merge it right away.

**Pull request merged**
