### PR TITLE
perf(theme-default): pre build svg in theme package

### PR DESCRIPTION
**Pull request by 10Derozan**
## Summary
Perf #682 

## Checklist

- [x] I have added changeset via `pnpm run change`.
- [ ] I have updated the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by 10Derozan** [comment]
!benchmark

**Comment by 10Derozan** [comment]
!benchmark

**Comment by 10Derozan** [comment]
@Timeless0911 Is this benchmark can be accessed?

**Comment by Timeless0911** [comment]
> accessed

what's accessed mean

**Comment by Timeless0911** [comment]
!bench

**Review by Timeless0911 — APPROVED** [review]

**Comment by Timeless0911** [comment]
兵贵神速！

**Pull request merged**
