### PR TITLE
feat: support extra head tags

### PR DESCRIPTION
**Pull request by toteto**
## Summary

This PR adds support for extra head tags per page via Frontmatter config. 

## Related Issue

#1121 

## Checklist

- [x] Tests updated (or not required).
- [x] Documentation updated (or not required).

### CODE REVIEW

**Comment by Timeless0911** [comment]
Thxs, can you add a seperate new fixture for this feature instead?

**Comment by toteto** [comment]
> Thxs, can you add a seperate new fixture for this feature instead?

Done in 598cdc9

**Comment by toteto** [comment]
Made changes as discussed in #1121

- Now the header attributes are being applied in the build step
- Made some changes to the `loadFrontMatter` typing so get better typing support on the build side.

@Timeless0911 please re-review

**Comment by toteto** [comment]
@Timeless0911 please also consider the extension to this PR #1168

**Comment by Timeless0911** [comment]
This PR looks like it can be closed now since #1168

**Comment by toteto** [comment]
> This PR looks like it can be closed now since #1168

Sounds good, only created it as separate PR to allow the one being approved and merged without the other in case it doesn't fit into the vision for Rspress.

Feel free to close this PR if not needed.

**Pull request closed without merging**
