### PR TITLE
fix(theme-default): the serial number of the two-digit number will become one digit. 10. -> 1.

### LINKED ISSUE #1083: [Bug]: The serial number of the two-digit number will become one digit. 10. -> 1.
### Version

```sh
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 127.59 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 124.0.6367.201
    Chrome Canary: 126.0.6475.0
    Safari: 17.2.1
  npmPackages:
    @rspress/plugin-container-syntax: 1.20.1 => 1.20.1 
    @rspress/plugin-playground: 1.20.1 => 1.20.1 
    @rspress/plugin-preview: 1.20.1 => 1.20.1 
    rspress: 1.20.1 => 1.20.1
```

### Details

````md
1. [Fork](https://help.github.com/articles/fork-a-repo/) the Rspack repository into your own GitHub account.
2. [Clone](https://help.github.com/articles/cloning-a-repository/) the repository to your local.
3. Checkout a new branch from `main`.
4. Set up the development environment, you can read the "Setup Development Environment" section below to learn about it.
5. If you've fixed a bug or added code that should be tested, then add some tests.
6. Make sure all the tests pass, you can read the "Testing" section below to learn about it.
7. Run `pnpm run lint:js` and `pnpm run lint:rs` to check the code style.
8. If you've changed some Node.js packages, you should add a new [changeset](https://github.com/changesets/changesets). Run `pnpm run changeset`, select the changed packages and add the changeset info.
9. If you've changed some Rust packages, you should add a new [changeset](https://github.com/changesets/changesets) for `@rspack/binding` package.
10. Submit the Pull Request, make sure all CI runs pass.
11. The maintainers will review your Pull Request soon.
````

image

`0. 1.` should be `10. 11.`

### Reproduce link

https://github.com/SoonIter/rspress-number-issue

### Reproduce Steps

1. ni 2. npm run dev

### PR DESCRIPTION
**Pull request by shulaoda**
## Summary
Fixed #1083 
## Related Issue
#1083 

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by shulaoda** [comment]
I think `padding-left` should be `24px` which is consistent without sidebar.

**Comment by Timeless0911** [comment]
image

What is the essential cause of this issue? When the list exceeds ten, the numbers will exceed the doc content block and be covered? Why not expand the width to the content block? Is the explorer behaviour of different kinds or versions matters?

**Comment by shulaoda** [comment]
image

This is because `::marker` is not considered a part of the size of the ol or ul container, so it needs to be spread out in a padding left manner.
We borrowed the style of `padding-left: 1.25rem` from vitepress which is used to solve the display of numbers below 10, but due to our content container not having `padding-left` in `@media(min-width: 960px)`, numbers above 10 will be masked.

**Comment by shulaoda** [comment]
image
Or it could be solved this way, but it may not be very friendly to digital content below 10 because it has a fixed placeholder.

**Comment by Timeless0911** [comment]
>  Or it could be solved this way, but it may not be very friendly to digital content below 10 because it has a fixed placeholder.

this is ugly hh

**Comment by Timeless0911** [comment]
@SoonIter Adding padding-left for doc content LGTM, what's your opinion of how to fix it?

**Comment by Timeless0911** [comment]
My obsessive-compulsive disorder makes me feel that misaligned numbers are still ugly. 

This tells us not to list more than ten steps when writing a document. This should be the standard for writing technical documents!

**Comment by SoonIter** [comment]
> @SoonIter Adding padding-left for doc content LGTM, what's your opinion of how to fix it? 

LGTM

**Review by SoonIter — APPROVED** [review]

**Pull request merged**
