### PR TITLE
feat(@rspress/plugin-container-syntax): support for gitHub markdown alert syntax!

### LINKED ISSUE #1424: [Feature]: Support for GitHub markdown alert syntax
### What problem does this feature solve?

Alerts are a Markdown extension based on the blockquote syntax that you can use to emphasize critical information. On GitHub, they are displayed with distinctive colors and icons to indicate the significance of the content.

- Preview:

image

- Ref:

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

### What does the proposed API look like?

The same as GitHub

### PR DESCRIPTION
**Pull request by ArnavK-09**
## Summary

`@rspress/plugin-container-syntax` updated to support github alerts markdown syntax, converts to container that is already supported by rspress with different syntax,
now it supports both syntax!

## Related Issue

fixes #1424
resolves #1424 

## Checklist

- [x] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by ArnavK-09** [comment]
@chenjiahan is this valid?

**Comment by Timeless0911** [comment]
👍 Awesome work, thanks! 
Some review suggestions from me:

1. More tests about `> [!NOTE]` / [!WARNING] / `[!CAUTION]` should be added.
2. `@rspress/plugin-container-syntax` only works when `markdown.mdxRs = false`, and for the default, we use mdx-rs to compile, which is located in https://github.com/web-infra-dev/mdx-rs/blob/main/crates/plugin_container/src/lib.rs. This is implemented with Rust, which may be a bit difficult for beginners. Do you want to challenge this?

**Comment by ArnavK-09** [comment]
> 👍 Awesome work, thanks! 
> 
> Some review suggestions from me:
> 
> 1. More tests about `> [!NOTE]` / `[!WARNING]` / `[!CAUTION]` should be added.
> 2. `@rspress/plugin-container-syntax` only works when `markdown.mdxRs = false`, and for the default, we use mdx-rs to compile, which is located in https://github.com/web-infra-dev/mdx-rs/blob/main/crates/plugin_container/src/lib.rs. This is implemented with Rust, which may be a bit difficult for beginners. Do you want to challenge this?

1. Ok I'll add some more tests soon
2. So the need is to implement this feature in mdx-rs, well that's a totally different repo and i surely try to add GitHub alert feature in mdx-rs if I'm able to
But atlast, for this repo I think it's valid pr to be merged, since container remark plugin also needs to have GitHub alert feature
So, after adding tests can I expect this pr to be merged under hacktoberfest 
Thanks

**Comment by Timeless0911** [comment]
Sure, this PR will be merged first. 

One more question, is these `@ts-ignore` expected to be in your code, can you write some explanations in comments?

**Comment by ArnavK-09** [comment]
@Timeless0911  hey  👋  is this alright?

**Review by Timeless0911 — APPROVED** [review]
LGTM, thank you!

**Comment by Timeless0911** [comment]
Once we support this syntax in mdxRs, we should remember to write docs of it~

**Pull request merged**
