### PR TITLE
feat(create_rspress): support cancel operation

### PR DESCRIPTION
**Pull request by lalalazero**
## Summary

Hi~ I noticed that create-rspress cannot exit during creation. I hope this could help.

## Checklist

- [x] I have added changeset via `pnpm run change`.
- [ ] I have updated the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by sanyuan0704** [comment]
Thank you

**Comment by sanyuan0704** [comment]
Maybe you can add changeset for patch change by the following tip:

image

**Comment by lalalazero** [comment]
> Maybe you can add changeset for patch change by the following tip:
> 
> image

Yes, sure thing. thank you for reminder~

**Comment by lalalazero** [comment]
Hi~ I added changeset, if anything is inappropriate just let me know.

**Pull request merged**
